auth0/ruby-auth0

lib/auth0/mixins/initializer.rb

We should probably have some integration tests, right? :)

Make the client work for API v1

---

lib/auth0/api/authentication_endpoints.rb
spec/lib/auth0/api/authentication_endpoints_spec.rb

defaults to 120 seconds per @woloski

allow setting impersonation ttl

---

lib/auth0/api/v2.rb
lib/auth0/api/v2/connections.rb
lib/auth0/exception.rb
spec/integration/lib/auth0/api/v2/api_connections_spec.rb
spec/lib/auth0/api/v2/connections_spec.rb
spec/support/credentials.rb

adds connection support for the api v2

Add connections

---

.gitignore
examples/ruby-on-rails-api/bin/bundle
examples/ruby-on-rails-api/bin/rails
examples/ruby-on-rails-api/bin/rake
examples/ruby-on-rails-api/bin/setup
lib/auth0/api/authentication_endpoints.rb
lib/auth0/mixins/initializer.rb
spec/lib/auth0/api/authentication_endpoints_spec.rb
spec/lib/auth0/client_spec.rb

It has not the best way of handling 'impersionate' method test.
https://github.com/auth0/ruby-auth0/issues/61

fixed rails api doesn't start, now impersionated links works with v2

---

lib/auth0/api/v2.rb
lib/auth0/api/v2/logs.rb
spec/lib/auth0/api/v2/logs_spec.rb

Add api v2 log endpoints to the gem

---

README.md
lib/auth0/api/v2/users.rb

This PR closes PR #65 and PR #51.

Add how to generate documentation to the README.md + patch_user

---

README.md

Cloning and building docs on my local machine was a hassle. Maybe this will help future devs.

Add a badge to documentation

---

auth0.gemspec

Update outdated dependency

---

lib/auth0/api/authentication_endpoints.rb
spec/integration/lib/auth0/api/api_authentication_spec.rb
spec/lib/auth0/api/authentication_endpoints_spec.rb
spec/spec_helper.rb
spec/spec_helper_full.rb
spec/spec_helper_unit.rb
spec/support/credentials.rb
spec/support/dummy_class.rb

https://github.com/auth0/ruby-auth0/issues/89
Addresses the above issue
Includes some misc. cleanup to the specs

Update /login to use /oauth/token

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md

Pulled from our [open source template](https://github.com/auth0/open-source-template/tree/master/.github).

Add issue and PR templates, CoC

---

CHANGELOG.md
lib/auth0/version.rb

See [milestone](https://github.com/auth0/ruby-auth0/milestone/2) and CHANGELOG below.

Release v4.6.0

---

lib/auth0/api/v2/jobs.rb
spec/integration/lib/auth0/api/v2/api_jobs_spec.rb
spec/lib/auth0/api/v2/jobs_spec.rb

Add `.export_users` to `Auth0::Api::V2::Jobs`

Added export users to jobs endpoint

---

CHANGELOG.md
DEPLOYMENT.md
lib/auth0/version.rb

Please see the [Milestone](https://github.com/auth0/ruby-auth0/issues?q=is%3Aclosed+milestone%3Av4.7.0) for changes

Release 4.7.0

---

lib/auth0/api/v2/roles.rb
lib/auth0/api/v2/users.rb
lib/auth0/mixins/validation.rb
spec/lib/auth0/api/v2/roles_spec.rb
spec/lib/auth0/api/v2/users_spec.rb

- Add all Roles endpoints for the Management API
- Fix Users permission arrays
Integration tests for these changes and #169 will be added in another PR

Add Management API Roles endpoints

---

lib/auth0/api/v2/users.rb
spec/lib/auth0/api/v2/users_spec.rb

Change unreleased `Users.remove_roles` to `Users.remove_user_roles`
- Missed this method in #173 
- Method added in #169

Change Users.remove_roles to remove_user_roles

---

lib/auth0/api/v2/users.rb

Deprecate Auth0::Api::V2::Users.delete_users

Deprecate Auth0::Api::V2::Users.delete_users

---

CHANGELOG.md
Gemfile.lock
lib/auth0/version.rb

See changelog below or [milestone](https://github.com/auth0/ruby-auth0/issues?q=is%3Aclosed+milestone%3Av4.8.0) for more information about this release.

Release 4.8.0

---

README.md

Adds information to the README about doing an automatic client credentials grant.
Closes #190

Update README with client_secret

---

DEPLOYMENT.md
README.md

Adds notes for running tests and setting up the release environment. 
Idea from https://github.com/auth0/ruby-auth0/pull/213#issuecomment-621752280

Add development notes

---

.env.example
DEPLOYMENT.md
README.md
spec/spec_helper.rb

This PR attempts to clarify how to test the library on a local machine, and sets up some environment files to make integration testing a little easier.
The diff also contains some auto formatting.
Related to #213 and #214

[SDK-1542] Updated info about testing in the readme

---

lib/auth0/api/v2/users.rb
spec/lib/auth0/api/v2/users_spec.rb

Add pagination to user permissions

Add pagination to user permissions

---

lib/auth0/api/v2.rb
lib/auth0/api/v2/branding.rb
spec/lib/auth0/api/v2/branding_spec.rb

Adds support for branding endpoints

Adds Branding [SDK-2485]

---

README.md

Adds idtoken validation guidance

Org idtoken validation guidance [SDK-2457]

---

CHANGELOG.md

Just a typo
Allows Dependabot to correctly source changelog
Ref: diowa/icare#770
n/a
n/a

Fix typo in version 5.1.1 link

---

CHANGELOG.md
lib/auth0/version.rb

[Full Changelog](https://github.com/auth0/ruby-auth0/compare/v5.2.0..v5.3.0)
**Added**
- Checkpoint Pagination [\#284](https://github.com/auth0/ruby-auth0/pull/284) ([davidpatrick](https://github.com/davidpatrick))

Release v5.3.0

---

.shiprc

Allows us to integrate with our internal shipping CLI.

Add .shiprc

---

Gemfile.lock

This PR updates the Gem.lockfile dependencies to address a vulnerability in `rails-html-sanitizer` <= 1.4.2
- https://www.cve.org/CVERecord?id=CVE-2022-32209

Security: Update dependencies lockfile

---

examples/ruby-api/Gemfile
examples/ruby-api/Gemfile.lock
examples/ruby-api/README.md

This PR fixes the built-in example app by upgrading Sinatra & Puma, to resolve a [security issue](https://nvd.nist.gov/vuln/detail/CVE-2022-29970).

Upgrade Sinatra in example app

---

lib/auth0/api/v2/organizations.rb

This is a small typo correction I saw while using this package. 
Small typo fix. There shouldn't need any testing.

Correct typo

---

Gemfile.lock

This PR updates `Gemfile.lock` to reflect latest dependency versions, and resolves Snyk warnings.
N/A

chore: Update Dependencies Lockfile

---

.semgrepignore

This PR adds a Semgrep ignore file (.semgrepignore) to the repository, to avoid introducing false warnings due to example code and documentation.
N/A

test: Create .semgrepignore

---

.github/workflows/snyk.yml
.github/workflows/test.yml

This PR:
- Fixes an issue with the Snyk workflow referencing an incorrect language type.
- Updates the `test` workflow to have greater specificity in its concurrency group.
N/A
N/A

ci: Update Workflows
