auth0/ruby-auth0

README.md
By following the existing api v2 basic usage example, a rather obscure error is generated - 'SocketError: getaddrinfo: Name or service not known'. Including this key/value pair as in api v1 makes it work.
=> Update readme.md api v2 basic usage example

lib/auth0/api/authentication_endpoints.rb
According to https://auth0.com/docs/protocols it's "openid".
=> Fix typo delegation signature; open_id => openid

lib/auth0/api/authentication_endpoints.rb, spec/lib/auth0/api/authentication_endpoints_spec.rb
https://auth0.com/docs/auth-api#!#post--users--user_id--impersonate
> Using this API you can generate a link that could be used to
> impersonate a user. This is useful for troubleshooting. Note: this API
> can only be used with the Global Client credentials.
=> Impersonation

lib/auth0/api/authentication_endpoints.rb, spec/lib/auth0/api/authentication_endpoints_spec.rb
To use with salesforce community auth it's required to pass extra parameters for delegation. See description of "Salesforce API" addon
=> allow to pass extra parameters to delegation method

lib/auth0/mixins/initializer.rb, spec/integration/lib/auth0/auth0_client_spec.rb
I'd like to discuss the idea of adding some client information to our API libraries — these changes would need to be implemented in a all of our official clients, as well as requiring some effort on the devops, and data tracking sides. I'll do my best to explain why this could be such a valuable enhancement.
---
Add two headers to all of our API clients when they're talking to auth0 APIs. These headers would carry the "platform" of the client, and the "version", so in the case of this Ruby client, it'd have the following two headers: 
```
User-Agent: Ruby/2.2.1 (Rails 4.2.2)
Auth0-Client: Ruby/3.4.1
```
To break it down a little bit: The client is "ruby" (language/sdk), and the version of ruby that we're using is `2.2.1`. The client version corresponds to the semantic version used for …
=> Client information headers

Rakefile, spec/spec_helper_full.rb
Tests were throwing this (integration tests)
```
Failure/Error: let!(:user) { client.create_user(email, password, connection, {
Auth0::BadRequest:
{"error"=>"bad.email", "error_description"=>"error in email - email format validation failed: _localdallas@example.net"}
```
=> email validation is broken by _, which breaks the tests

lib/auth0/api/v2/users.rb
The `search_engine` param must be set in order to use the `q` param
=> set the search engine if a query is set

lib/auth0/api/authentication_endpoints.rb, spec/lib/auth0/api/authentication_endpoints_spec.rb
Adding support to the authentication endpoints to be able to send in a refresh token and get a new unexpired JWT.
=> Refresh token delegation

.travis.yml, Gemfile, auth0.gemspec, lib/auth0/mixins/httparty_proxy.rb, spec/lib/auth0/mixins/httparty_proxy_spec.rb
Previously, Auth0::Exception was being fed a Hash for its message content.
All messages are stringified, so when a user accesses the error message,
they are left with a string representation of a hash. Here is an example.
```ruby
def some_method
auth0_client.user('notarealuser')
rescue Auth0::Exception => e
puts e.message # => "{\"statusCode\"=>400, \"error\"=>\"Bad Request\", \"message\"=>\"Path validation error: 'String does not match pattern ^.+\\\\|.+$: 3241312' on property id (The user_id of the user to retrieve).\", \"errorCode\"=>\"invalid_uri\"}"
end
```
These hash representations do not have an efficient, robust parsing mechanism.
Therefore, I propose we simply use the JSON representation from the response
body as the message, so users can parse the message and do what they need …
=> Use JSON (result.body) for exception messages in requests

examples/ruby-on-rails-api/Gemfile, examples/ruby-on-rails-api/app/controllers/secured_ping_controller.rb, examples/ruby-on-rails-api/app/models/User.rb, examples/ruby-on-rails-api/config/initializers/knock.rb
=> updated dependencies in ror api example. Fix #75

README.md
API Version must be an integer, otherwise api_v1?(options) returns false and the API thinks you're intending to use the v2 API.
=> Resolve v1 API example error

lib/auth0/exception.rb, lib/auth0/mixins/httpproxy.rb
If `RestClient` _actually_ times out, the current code breaks.
Probably because there is no `e.reponse` in the case of a timeout.
I couldn't run the specs, so could someone maybe help out?
=> Introduce and raise exception for timeout

spec/integration/lib/auth0/api/v2/api_client_grants_spec.rb, spec/integration/lib/auth0/api/v2/api_clients_spec.rb, spec/integration/lib/auth0/api/v2/api_connections_spec.rb, spec/integration/lib/auth0/api/v2/api_device_credentials_spec.rb, spec/integration/lib/auth0/api/v2/api_email_spec.rb, spec/integration/lib/auth0/api/v2/api_logs_spec.rb, spec/integration/lib/auth0/api/v2/api_resource_servers_spec.rb, spec/integration/lib/auth0/api/v2/api_rules_spec.rb, spec/integration/lib/auth0/api/v2/api_stats_spec.rb, spec/integration/lib/auth0/api/v2/api_tenants_spec.rb, spec/integration/lib/auth0/api/v2/api_tickets_spec.rb, spec/integration/lib/auth0/api/v2/api_users_spec.rb
Add delay to integration test in order to avoid 429 error for exceeding API rate limit.
=> Add delay to integration test

lib/auth0/api/v2.rb, lib/auth0/api/v2/users_by_email.rb, spec/lib/auth0/api/v2/users_by_email_spec.rb
Hey, we would like to use the `users-by-email` API. I've tested locally against auth0 and it seems to be working fine. Should I also add an integration test?
Thanks!
API docs https://auth0.com/docs/api/management/v2#!/Users_By_Email/get_users_by_email
=> Add support to /api/v2/users-by-email

README.md
I believe the integer passed into as timeout is used as seconds in the rest_client gem. This PR simply updates the readme and fixes the misleading typo. 😄
=> Fix error in the readme regarding timeouts

lib/auth0/api/authentication_endpoints.rb, spec/lib/auth0/api/authentication_endpoints_spec.rb
This PR changes the default `grant_type` option in `AuthenticationEndpoints#login` from the value of the password parameter to "password". It also updates the spec to use a test password other than "password" to verify that the default grant type is set correctly.
=> Correctly default grant_type to 'password' in login method

Gemfile
This PR switches the Gemfile over to use the HTTPS RubyGems source, as advised by running `bundle audit` on the project.
=> Use Secure RubyGems Source

lib/auth0/api/v2/clients.rb, lib/auth0/api/v2/connections.rb, spec/integration/lib/auth0/api/v2/api_clients_spec.rb, spec/lib/auth0/api/v2/clients_spec.rb, spec/lib/auth0/api/v2/connections_spec.rb, spec/spec_helper.rb, spec/spec_helper_full.rb
- Add new `:page` and `:per_page` method parameters to `Auth0::Api::V2::Clients` and `Auth0::Api::V2::Connections` modules.
- Add ability to pass an `Array` for the `fields:` parameter and convert to comma-sep string
- Add tests for all changes above.
=> Add pagination and tests to Clients and Connections endpoints

lib/auth0/api/v2/users.rb, spec/integration/lib/auth0/api/v2/api_users_spec.rb, spec/lib/auth0/api/v2/users_spec.rb
- Replace the hard-coded search engine version `v2` with a modifiable one
- Improve docs for the method
- Add unit and integration tests
- Remove skipped user test
=> Add search_engine parameter to Users endpoint + tests

lib/auth0/api/v2/client_grants.rb, spec/integration/lib/auth0/api/v2/api_client_grants_spec.rb, spec/lib/auth0/api/v2/client_grants_spec.rb
- Add `page` and `per_page` parameters to `Auth0::Api::V2::ClientGrants::client_grants` endpoint
- Add unit and integration tests for this change
- Remove `sleep` directives from the client grant integration tests
=> Add pagination and tests for Client Grants

lib/auth0/api/v2/rules.rb, spec/integration/lib/auth0/api/v2/api_rules_spec.rb, spec/lib/auth0/api/v2/rules_spec.rb, spec/spec_helper_full.rb
- Add `page` and `per_page` parameters to `Auth0::Api::V2::Rules::rules` endpoint
- Add unit and integration tests for this change
- Remove `sleep` directives from the rules integration tests
=> Add pagination and tests for Rules endpoint

lib/auth0/api/authentication_endpoints.rb, spec/lib/auth0/api/authentication_endpoints_spec.rb
- Add a second parameter to include the Client ID
- Add a third parameter to do federated
- Update URL to `v2` logout
Closes #81
=> Add Client ID to logout_url

lib/auth0/api/authentication_endpoints.rb
- Update docs links
- More clear descriptions and param names
=> Fix docblocks for Authentication API endpoints

lib/auth0/api/authentication_endpoints.rb, spec/integration/lib/auth0/api/api_authentication_spec.rb, spec/lib/auth0/api/authentication_endpoints_spec.rb
- Change `URI.escape` -> `CGI.escape`, as recommended by Rubocop
- Formatting and cleanup on tests for methods that are not being replaced/deprecated
=> Clean up auth endpoint tests

lib/auth0/api/authentication_endpoints.rb
**Note:** No functional changes, just an added docblock line and moving the methods in the file. 
- `phone_login` - Uses the legacy oauth/ro endpoint. Use a Password Grant instead.
- `token_info` - Uses the legacy tokeninfo endpoint. Refer to `user_info` method.
- `delegation` - Endpoint is disabled for new tenants. [Refer to migration guide](https://auth0.com/docs/migrations#api-authorization-with-third-party-vendor-apis).
- `refresh_delegation` - Feature is disabled for new tenants. [Refer to migration guide](https://auth0.com/docs/migrations#api-authorization-with-third-party-vendor-apis).
- `impersonate` - Endpoint is disabled. Replacement forthcoming.
- `unlink_user` - Endpoint is deprecated. [Refer to API v2](https://auth0.com/docs/api/management/v2#!/Users/delete_user_identity_by_us …
=> Deprecate Authentication API endpoints

lib/auth0/api/authentication_endpoints.rb, spec/lib/auth0/api/authentication_endpoints_spec.rb
Add `options` parameter to `wsfed_url` method + tests
=> Add additional parameters for WS-Fed URL

lib/auth0/mixins/initializer.rb
This module depends on JSON but doesn't load it. This commit makes that dependency explicit so the application doesn't have to load it.
In all fairness, it's pretty likely that the app _does_ load the `json` gem/stdlib (which is why this has been able to go unnoticed), but we should always load our own dependencies. :-)
=> Explicitly require JSON dependency

lib/auth0/api/authentication_endpoints.rb, lib/auth0/mixins/httpproxy.rb, spec/fixtures/vcr_cassettes/Auth0_Api_AuthenticationEndpoints/_change_password/should_trigger_a_password_reset.yml, spec/fixtures/vcr_cassettes/Auth0_Api_AuthenticationEndpoints/_saml_metadata/should_retrieve_SAML_metadata.yml, spec/fixtures/vcr_cassettes/Auth0_Api_AuthenticationEndpoints/_userinfo/should_fail_as_not_authorized.yml, spec/fixtures/vcr_cassettes/Auth0_Api_AuthenticationEndpoints/_userinfo/should_return_the_userinfo.yml, spec/fixtures/vcr_cassettes/Auth0_Api_AuthenticationEndpoints/_wsfed_metadata/should_retrieve_WSFED_metadata.yml, spec/fixtures/vcr_cassettes/Auth0_Api_AuthenticationEndpoints/create_test_user.yml, spec/fixtures/vcr_cassettes/Auth0_Api_AuthenticationEndpoints/delete_test_user.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Blacklists/_add_token_to_blacklist/should_add_a_token_to_the_blacklist.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Blacklists/_blacklisted_tokens/should_get_the_added_token_from_the_blacklist.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_DeviceCredentials/_device_credentials/_filter_by_type/should_exclude_the_test_credential.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_DeviceCredentials/_device_credentials/should_have_at_least_1_entry.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_DeviceCredentials/_device_credentials/should_include_the_test_credential.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_DeviceCredentials/create_test_credential.yml, spec/integration/lib/auth0/api/api_authentication_spec.rb, spec/lib/auth0/api/authentication_endpoints_spec.rb, spec/spec_helper.rb
- Add new `userinfo` method for `Auth0::Api::AuthenticationEndpoints`
- Add the ability to include additional headers in `get` method in `Auth0::Mixins::HTTPProxy`
- Add note to deprecate previous `user_info` method
=> Add new userinfo method for auth endpoints

lib/auth0/api/authentication_endpoints.rb, lib/auth0/api/v2/client_grants.rb, lib/auth0/api/v2/device_credentials.rb, lib/auth0/api/v2/logs.rb, lib/auth0/api/v2/resource_servers.rb, lib/auth0/api/v2/users.rb, lib/auth0/api/v2/users_by_email.rb
When I run `bundle exec rake documentation` I got warnings
<details>
```
[warn]: @param tag has unknown parameter name: q
in file `lib/auth0/api/v2/logs.rb' near line 24
[warn]: @param tag has unknown parameter name: page
in file `lib/auth0/api/v2/logs.rb' near line 24
[warn]: @param tag has unknown parameter name: per_page
in file `lib/auth0/api/v2/logs.rb' near line 24
[warn]: @param tag has unknown parameter name: sort
in file `lib/auth0/api/v2/logs.rb' near line 24
[warn]: @param tag has unknown parameter name: fields
in file `lib/auth0/api/v2/logs.rb' near line 24
[warn]: @param tag has unknown parameter name: include_fields
in file `lib/auth0/api/v2/logs.rb' near line 24
[warn]: @param tag has unknown parameter name: include_totals
in file `lib/auth0/api/v2/logs.rb' near line 24 …
```
=> Documentation improvements

lib/auth0/api/v2/tickets.rb, spec/lib/auth0/api/v2/tickets_spec.rb
Add ttl_sec argument to post_email_verification request. 
The post_email_verification endpoint supports a ttl_sec parameter which this gem does not currently support. See: https://auth0.com/docs/api/management/v2#!/Tickets/post_email_verification
The tickets spec was adjusted to include the relevant change here. Admittedly this is blind as I couldn't for the life of me figure our how to run the specs. If anyone can point me to some documentation or guide me through this then that would be great - otherwise I assume this is a relatively non-impactful change and shouldn't break anything.
=> Add ttl_sec argument to post_email_verification request.

lib/auth0/api/authentication_endpoints.rb, spec/lib/auth0/api/authentication_endpoints_spec.rb
- Add `Auth0::Api::AuthenticationEndpoints.exchange_refresh_token` method.
- Remove requirement for `:redirect_uri` param in the `exchange_auth_code_for_tokens`method
Closes #111 
Also add a test for `exchange_auth_code_for_tokens` with custom params.
=> Add refresh token method and unit tests

lib/auth0/api/authentication_endpoints.rb
- Add deprecation notices on the following methods:
- `Auth0::Api::AuthenticationEndpoints.obtain_access_token`
- `Auth0::Api::AuthenticationEndpoints.obtain_user_tokens`
- `Auth0::Api::AuthenticationEndpoints.login`
- `Auth0::Api::AuthenticationEndpoints.user_info`
- Ran `rubocop` in `Auth0::Api::AuthenticationEndpoints` and fixed issues
=> Formal deprecation of 4 auth endpoint methods; rubocop

lib/auth0/api/v2/resource_servers.rb, spec/fixtures/vcr_cassettes/Auth0_Api_V2_ResourceServers/_delete_resource_server/should_delete_the_test_server_without_an_error.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_ResourceServers/_resource_server/should_get_the_test_server.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_ResourceServers/_resource_servers/should_get_the_test_server.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_ResourceServers/_resource_servers/should_return_at_least_1_result.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_ResourceServers/_resource_servers/should_return_the_first_page_of_one_result.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_ResourceServers/create_test_server.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_ResourceServers/delete_test_server.yml, spec/integration/lib/auth0/api/v2/api_resource_servers_spec.rb, spec/lib/auth0/api/v2/resource_servers_spec.rb, spec/spec_helper.rb
Adds `Auth0::Api::V2::ResourceServers#resource_servers` method (and alias `get_resource_servers`) to fetch all Resource Servers in the tenant.
Discussion in #154 
(my testing was done on 2.4.4, not 2.6.0)
=> Get all resource servers

lib/auth0/api/v2/tickets.rb, spec/lib/auth0/api/v2/tickets_spec.rb
Updates the `post_password_change` method to contain a few new parameters based on the [auth0 docs]:
- `mark_email_as_verified` - if true, this marks the user's email as verified after they change their password
- `includeEmailInRedirect` - if true, this includes the user's email address as part of the returnUrl
- `ttl_sec` - The TTL of the ticket
Additionally, I reordered the params to match the auth0 documentation. This might be a breaking change, I'm not a proficient-enough rubyist to know.
[Auth0 "Create a password change ticket" documentation][auth0 docs]
Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should …
=> More password change params

lib/auth0/api/v2/resource_servers.rb, spec/integration/lib/auth0/api/v2/api_resource_servers_spec.rb, spec/lib/auth0/api/v2/resource_servers_spec.rb
Adds a `patch_resource_server` method that takes a resource server id and a hash of options. Includes spec tests that pass and tentative integration tests awaiting VCR cassettes.
Discussion in #156.
=> Add patch resource server

lib/auth0/api/v2/jobs.rb, lib/auth0/mixins/httpproxy.rb, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Jobs/_export_users_and_get_job/should_create_an_export_users_job_successfully.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Jobs/_export_users_and_get_job/should_get_the_export_users_job.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Jobs/_import_users_and_get_job/should_create_an_import_users_job_successfully.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Jobs/_import_users_and_get_job/should_get_the_import_users_job.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Jobs/_send_verification_email_and_get_job/should_create_a_new_verification_email_job.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Jobs/_send_verification_email_and_get_job/should_get_the_completed_verification_email.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Jobs/_send_verification_email_and_get_job/should_reject_an_invalid_client_id.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Jobs/delete_imported_user.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Jobs/search_for_connection_id.yml, spec/integration/lib/auth0/api/v2/api_jobs_spec.rb, spec/integration/lib/auth0/api/v2/api_resource_servers_spec.rb, spec/lib/auth0/api/v2/jobs_spec.rb, spec/spec_helper.rb
- Add Add Client ID to `Auth0::Api::V2::Jobs.send_verification_email`
- Remove skipped Jobs tests and add VCR cassettes
Fixes #92 
[Failing tests for new feature](https://travis-ci.org/auth0/ruby-auth0/builds/499524045)
=> Add Client ID to send_verification_email

lib/auth0/api/v2/users.rb, lib/auth0/mixins/permission_struct.rb, spec/lib/auth0/api/v2/users_spec.rb
Adds all missing User endpoints:
- `Auth0::Api::V2::Users.get_roles`
- `Auth0::Api::V2::Users.remove_roles`
- `Auth0::Api::V2::Users.add_roles`
- `Auth0::Api::V2::Users.get_enrollments`
- `Auth0::Api::V2::Users.get_permissions`
- `Auth0::Api::V2::Users.remove_permissions`
- `Auth0::Api::V2::Users.add_permissions`
- `Auth0::Api::V2::Users.generate_recovery_code`
- `Auth0::Api::V2::Users.invalidate_browsers`
Will add integration tests in another PR after Roles
=> Add missing User Management API endpoints

lib/auth0/api/v2.rb, lib/auth0/api/v2/roles.rb, lib/auth0/api/v2/users.rb, spec/lib/auth0/api/v2/roles_spec.rb, spec/lib/auth0/api/v2/users_spec.rb
Renaming a few unreleased `Auth0::Api::V2::Users` and `Auth0::Api::V2::Roles` methods to avoid collisions. 
- Related to #169 
- Related to #172
=> Change new Role and User methods to avoid collision

spec/integration/lib/auth0/auth0_client_spec.rb, spec/support/credentials.rb
Hard-code test values when no `.env` is present or a required value is missing.
Will allow forked PRs like #176 and #177 to run and pass. 
=> Remove reliance on .env values for tests

lib/auth0/api/v2/jobs.rb, spec/lib/auth0/api/v2/jobs_spec.rb
Add request parameters for users imports endpoint.
(upsert / external_id / send_completion_email)
https://auth0.com/docs/api/management/v2/#!/Jobs/post_users_imports
=> Add parameters for users imports

lib/auth0/api/v2/jobs.rb, spec/lib/auth0/api/v2/jobs_spec.rb
Add endpoint for failed job error details.
https://auth0.com/docs/api/management/v2#!/Jobs/get_errors
=> Add failed job error details endpoint

auth0.gemspec
Gemspec: Drop EOL'd property rubyforge_project.
The RubyGems property rubyforge_project is removed without a replacement.
- Does `gem build` still work?
=> Gemspec: Drop EOL'd property rubyforge_project

lib/auth0/exception.rb, lib/auth0/mixins/httpproxy.rb, spec/lib/auth0/mixins/httpproxy_spec.rb, spec/support/stub_response.rb
This PR adds a new exception class, Auth0::RateLimitEncountered. In addition to the message and backtrace, this exception has attributes to hold the values of the [Auth0 Rate Limiting Headers](https://auth0.com/docs/policies/rate-limits#http-response-headers).
Thus, you can get access to this information when you encountered rate limiting, for example:
```ruby
try_again = true
begin
auth0.clients
rescue Auth0::RateLimitEncountered => e
if try_again
try_again = false
warn("Rate limiting encountered, waiting until #{Time.at(e.reset)} to try again")
sleep(e.reset - Time.now.to_i)
retry
else
raise e
end
end
```
This pull request address #158 
A future improvement might incorporate (optional) automatic retry-after-wait into the gem itself, but for now exposing the required information to …
=> Expose rate limiting information

lib/auth0/api/v2/guardian.rb, lib/auth0/api/v2/roles.rb, lib/auth0/api/v2/users.rb, lib/auth0/mixins.rb, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Roles/_add_role_permissions/should_add_a_Permission_to_the_Role_successfully.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Roles/_add_role_users/should_add_a_User_to_the_Role_successfully.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Roles/_delete_role/should_delete_the_Role_successfully.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Roles/_get_role/should_get_the_Role_successfully.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Roles/_get_role_permissions/should_get_exactly_1_Permission.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Roles/_get_role_permissions/should_get_the_added_Permission_from_the_Role_successfully.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Roles/_get_role_users/should_get_exactly_1_User.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Roles/_get_role_users/should_get_the_added_User_from_the_Role_successfully.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Roles/_get_roles/should_get_the_Role_successfully.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Roles/_remove_role_permissions/should_remove_a_Permission_from_the_Role_successfully.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Roles/_update_role/should_update_the_Role_successfully.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Roles/create_test_api.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Roles/create_test_role.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Roles/create_test_user.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Roles/delete_test_api.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Roles/delete_test_user.yml, spec/integration/lib/auth0/api/v2/api_roles_spec.rb, spec/spec_helper.rb
- Add the missing mixin to `lib/auth0/mixins.rb
- Move all mixin requires to that file and adjust order (aesthetic)
**Note for reviewers:** You can ignore everything in `spec/fixtures/vcr_cassettes`, just recorded HTTP interactions.
Closes #192 
Adjusted the `spec_helper` requires to catch missing required files in the future.
=> Add missing Permissions mixin

CHANGELOG.md, Gemfile.lock, auth0.gemspec, lib/auth0/version.rb
See [milestone](https://github.com/auth0/ruby-auth0/issues?q=is%3Aclosed+milestone%3Av4.9.0) or CHANGELOG below for fixes and additions in this release. 
This PR also includes updates to development gems.
=> Release 4.9.0

.rubocop.yml, Gemfile, Gemfile.lock
Fix Warning: unrecognized cop Rails found in .rubocop.yml
- https://github.com/rubocop-hq/rubocop/pull/7071
- https://github.com/rubocop-hq/rubocop-rails
=> add rubocop-rails

lib/auth0/api/v2/client_grants.rb, spec/lib/auth0/api/v2/client_grants_spec.rb
I'd like to fetch a client grant by its client id. 
We can't call `Auth0::Api::V2::ClientGrants#client_grants` with `client_id` while `GET /api/v2/client-grants` accepts `client_id`.
Public doc for `GET /api/v2/client-grants`
https://auth0.com/docs/api/management/v2#!/client_grants/get_client_grants
- I'm very happy with adding integration tests for this but I can't run `master`'s integration tests on my local.
* No. But `master` also fails.
=> Pass client_id, audience at Auth0::Api::V2::ClientGrants#client_grants

lib/auth0/api/v2/roles.rb, spec/lib/auth0/api/v2/roles_spec.rb
This PR adds support for the `name_filter` parameter on the `get_roles` [endpoint](https://auth0.com/docs/api/management/v2#!/Roles/get_roles) to filter roles by name.
=> Added support for name_filter parameter [SDK-1607]

CHANGELOG.md, Gemfile.lock, lib/auth0/version.rb
**Added**
- Added support for name\_filter parameter \[SDK-1607\] [\#214](https://github.com/auth0/ruby-auth0/pull/214) ([Widcket](https://github.com/Widcket))
- Pass client\_id, audience at Auth0::Api::V2::ClientGrants\#client\_grants [\#209](https://github.com/auth0/ruby-auth0/pull/209) ([hkdnet](https://github.com/hkdnet))
- Add rubocop-rails [\#200](https://github.com/auth0/ruby-auth0/pull/200) ([tknzk](https://github.com/tknzk))
**Security**
- Update rack requirement from ~\> 1.6.4 to ~\> 2.1.2 [\#206](https://github.com/auth0/ruby-auth0/pull/206) ([dependabot[bot]](https://github.com/apps/dependabot))
- Update rake requirement from ~\> 10.4 to ~\> 13.0 [\#207](https://github.com/auth0/ruby-auth0/pull/207) ([dependabot[bot]](https://github.com/apps/dependabot))
- Update dependencies …
=> Release 4.10.0

lib/auth0/api/authentication_endpoints.rb, spec/lib/auth0/api/authentication_endpoints_spec.rb
Following https://community.auth0.com/t/passwordless-connection-not-working-for-tenants-created-after-jan-2-2020/36415/5 , it is now required to send `client_secret` through the passwordless endpoints.
This PR simply adds `client_secret` to the POST requests, following this spec.
PR tested on my app. Fails before (error `Auth0::AccessDenied: {"error":"unauthorized_client","error_description":"Client authentication is required"}`), pass after.
This PR replaces #213
=> [SDK-1542] Add client secret to Passwordless flow since it is now required

lib/auth0/api/authentication_endpoints.rb, lib/auth0/mixins/validation.rb, spec/lib/auth0/api/authentication_endpoints_spec.rb, spec/lib/auth0/mixins/validation_spec.rb
This update improves the SDK support for **OpenID Connect (OIDC)**. In particular, it adds support for **claims validation**.
- The implementation of the `validate_claims` method. Plus tests.
- Moved the params validation to the validator class, along with its tests.
- Replaced the public API test cases with ones that test just the logic inside that method.
=> Improve OIDC compliance: add claims validation support [SDK-987]

Gemfile.lock, README.md, auth0.gemspec, lib/auth0.rb, lib/auth0/algorithm.rb, lib/auth0/api/authentication_endpoints.rb, lib/auth0/exception.rb, lib/auth0/mixins/validation.rb, spec/lib/auth0/api/authentication_endpoints_spec.rb, spec/lib/auth0/mixins/validation_spec.rb, spec/spec_helper.rb
This update improves the SDK support for OpenID Connect. In particular, it modifies the sign in verification phase by substituting backchannel based checks with id_token validation.
**This PR aggregates a series of previously reviewed and approved PRs:**
- https://github.com/auth0/ruby-auth0/pull/224
- https://github.com/auth0/ruby-auth0/pull/223
- https://github.com/auth0/ruby-auth0/pull/222
- A new public method in `Auth0::Client` called `validate_id_token` that performs ID Token validation.
- `Auth0::Algorithm::HS256` and `Auth0::Algorithm::RS256`, classes that represent the signing algorithms and encapsulate the logic to obtain the respective secret/public keys.
- A new exception `Auth0::InvalidIdToken`.
None.
=> Improve OIDC compliance [SDK-987]

lib/auth0/mixins/validation.rb, spec/lib/auth0/mixins/validation_spec.rb
According to the spec, checking this value should be optional. Presence check however is not. That remains.
https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation
> The iat Claim **can** be used to reject tokens that were issued too far away from the current time, limiting the amount of time that nonces need to be stored to prevent attacks. The acceptable range is Client specific.
=> Remove iat claim value check

lib/auth0/api/v1/clients.rb, lib/auth0/api/v1/connections.rb, lib/auth0/api/v1/logs.rb, lib/auth0/api/v1/rules.rb, lib/auth0/api/v1/users.rb
Added warning to v1 calls.  These endpoints are no longer available for public saas customers
=> Deprecate mgmt v1 calls

lib/auth0/api/v2.rb, lib/auth0/api/v2/log_streams.rb, spec/lib/auth0/api/v2/log_streams_spec.rb
Adding support for the log-streams endpoints:
GET /api/v2/log-streams
GET /api/v2/log-streams/{id}
POST /api/v2/log-streams
PATCH /api/v2/log-streams/{id}
DELETE /api/v2/log-streams/{id}
- https://auth0.com/docs/api/management/v2#!/Log_Streams/get_log_streams
- https://auth0.com/docs/api/management/v2#!/Log_Streams/get_log_streams_by_id
- https://auth0.com/docs/api/management/v2#!/Log_Streams/post_log_streams
- https://auth0.com/docs/api/management/v2#!/Log_Streams/delete_log_streams_by_id
- https://auth0.com/docs/api/management/v2#!/Log_Streams/patch_log_streams_by_id
=> Add log streaming endpoints

lib/auth0/api/v2/jobs.rb, lib/auth0/api/v2/tickets.rb, spec/integration/lib/auth0/api/v2/api_jobs_spec.rb, spec/integration/lib/auth0/api/v2/api_tickets_spec.rb, spec/lib/auth0/api/v2/jobs_spec.rb, spec/lib/auth0/api/v2/tickets_spec.rb
Adds support for specifying the (optional) `identity` object when creating email verification tickets or jobs. This is needed when verifying emails when the primary is social, enterprise, or passwordless. Also needed to verify secondary identities.
- https://auth0.com/docs/api/management/v2#!/Tickets/post_email_verification
- https://auth0.com/docs/api/management/v2#!/Jobs/post_verification_email
=> New Email Verification Fields

lib/auth0/mixins/httpproxy.rb, spec/lib/auth0/mixins/httpproxy_spec.rb
URI.escape has been deprecated since version 2.7.0 https://ruby-doc.org/stdlib-2.7.0/libdoc/uri/rdoc/URI/Escape.html#method-i-escape-label-Description
Addressable gem covers what we need
Closes https://github.com/auth0/ruby-auth0/issues/202
=> Addressable URI Escape

lib/auth0/api/authentication_endpoints.rb, lib/auth0/mixins/access_token_struct.rb, lib/auth0/mixins/api_token_struct.rb, lib/auth0/mixins/permission_struct.rb, lib/auth0/mixins/validation.rb, spec/integration/lib/auth0/api/v2/api_roles_spec.rb, spec/integration/lib/auth0/api/v2/api_users_spec.rb, spec/lib/auth0/api/v2/roles_spec.rb, spec/lib/auth0/api/v2/users_spec.rb
Structs defined in lib/auth0/mixins are currently defined as top-level
constants (e.g. `AccessToken`). However, these names are popular and can
conflict with existing classes and break the client application.
Therefore, I'd like to put them as children of `Auth0` module.
Closes #201 
=> Don't define structs as top-level constants

CHANGELOG.md, Gemfile.lock, auth0.gemspec
Addressable dependency was only avail in development environments through webmock.  It should be included in the Gemfile
=> Addressable dependency

CHANGELOG.md, Gemfile.lock, lib/auth0/version.rb
This release addresses some long standing issues with the library that could only be addressed in a major.  We have also removed Api/v1 endpoints and other deprecated methods.
The following top level structs were colliding with other libraries, this was addressed in [\#183](183) and have been namespaced with `::Auth0::`
- `ApiToken` changed to `::Auth0::ApiToken`
- `Permission` changed to `::Auth0::Permission`
- `AccessToken` changed to `::AccessToken::AccessToken`
This method was requiring you send in a `name`, which was optional, but didn't require `connection_name` which isn't optional. This was fixed in [\#244](244).
`Auth0::Api::V2::Users.create_user(name, options = {})` has changed to `Auth0::Api::V2::Users.create_user(connection_name, options = {})`
APIv1 endpoints were deprecated …
=> Release 5.0.0

lib/auth0/api/v2/users.rb, spec/lib/auth0/api/v2/users_spec.rb
There seems to be a typo in the URL to regenerated the 2FA recovery codes.
Please describe both what is changing and why this is important. Include:
The correct URL can be found here: https://auth0.com/docs/api/management/v2#!/Users/post_recovery_code_regeneration
=> Fixes recovery-code-regeneration URL

CHANGELOG.md, lib/auth0/version.rb
[Full Changelog](https://github.com/auth0/ruby-auth0/compare/v5.0.0..v5.0.1)
**Added**
- Add test support for Ruby 2.6 and 2.7 and 3.0 [\#256](https://github.com/auth0/ruby-auth0/pull/256) ([fursich](https://github.com/fursich))
**Fixed**
- Fixes recovery-code-regeneration URL [\#257](https://github.com/auth0/ruby-auth0/pull/257) ([epintos](https://github.com/apps/epintos))
**Security**
- Bumps nokogiri from 1.10.10 to 1.11.1 [\#258](https://github.com/auth0/ruby-auth0/pull/258) ([dependabot](https://github.com/apps/dependabot))
=> Release 5.0.1

lib/auth0/api/v2/connections.rb, spec/lib/auth0/api/v2/connections_spec.rb
Hi, Thank you for Great Gem.
I added name param to Connections api because I couldn't pass the name parameter even though it exists.
https://auth0.com/docs/api/management/v2#!/Connections/get_connections
Rubocop was failing before the change...
=> add name param to connections api

README.md, lib/auth0/api/authentication_endpoints.rb, lib/auth0/mixins/validation.rb, spec/lib/auth0/mixins/validation_spec.rb
This PR adds support for Organizations (currently in a closed beta)
* documents passing the organization and invitation parameters to the authorize url builder
* adds id token validation for organization
=> Add Organizations support to Authentication API Client

.circleci/config.yml, lib/auth0/api/v2.rb, lib/auth0/api/v2/jobs.rb, lib/auth0/api/v2/organizations.rb, lib/auth0/api/v2/tickets.rb, lib/auth0/api/v2/users.rb, lib/auth0/exception.rb, spec/lib/auth0/api/v2/jobs_spec.rb, spec/lib/auth0/api/v2/organizations_spec.rb, spec/lib/auth0/api/v2/tickets_spec.rb, spec/lib/auth0/api/v2/users_spec.rb
Adds and updates endpoints to manage Organizations through the Management API
**Organizations**
POST Organization
PATCH Organization
GET Organizations
GET Organization
GET Organization (by name)
DELETE Organization
**Connections**
POST Organization Connection
PATCH Organization Connection
GET Organization Connections
GET Organization Connection
DELETE Organization Connection
**Members**
POST Organization Members
GET Organization Members
DELETE Organization Members
**Member Roles**
POST Organization Member Roles
GET Organization Member Roles
DELETE Organization Member Roles
**Invitations**
POST Organization Invitations
GET Organization Invitations
GET Organization Invitation
DELETE Organization Invitations
**Users**
GET User organizations
---- 
**Email Verification**
POST Email …
=> Organizations feature

README.md, lib/auth0/api/authentication_endpoints.rb, lib/auth0/mixins/initializer.rb, spec/lib/auth0/client_spec.rb
I'd like to fetch a api token with audience that my api identifier.
When I use auth0 with custom domain, I need to specify an audience that is different than the domain. 
But I can not unable to do this now.
The `:audience` parameter is synonymous with the OIDC ID Token and is also used to generate the login URL, so it's confusing.
Auth0's Client Credentials Flow asks the audience for[ an API identifier](https://auth0.com/docs/api/authentication#client-credentials-flow).
`:custome_domein` and `:sub` were suggested at #189 , but I thought there was a more direct way to express it.
so I think the parameter `:api_identifier` is not confusing, What are your thoughts?
This issue has been discussed at #189  as well.
Please describe how this can be tested by reviewers. Be specific about anything …
=> Add api_identifier as an accepted configurable

CHANGELOG.md, lib/auth0/version.rb
[Full Changelog](https://github.com/auth0/ruby-auth0/compare/v5.0.1..v5.1.0)
**Added**
- Org idtoken validation guidance  [\#267](https://github.com/auth0/ruby-auth0/pull/267) ([davidpatrick](https://github.com/davidpatrick))
- Adds Branding endpoints [\#266](https://github.com/auth0/ruby-auth0/pull/266) ([davidpatrick](https://github.com/davidpatrick))
- Organizations feature [\#264](https://github.com/auth0/ruby-auth0/pull/264) ([davidpatrick](https://github.com/davidpatrick))
- Add Organizations support to Authentication API Client [\#263](https://github.com/auth0/ruby-auth0/pull/263) ([davidpatrick](https://github.com/davidpatrick))
- Add api_identifier as an accepted configurable [\#261](https://github.com/auth0/ruby-auth0/pull/261) ([QWYNBG](https://github.com/QWYNBG))
- add name …
=> Release 5.1.0

lib/auth0/api/v2/organizations.rb, spec/lib/auth0/api/v2/organizations_spec.rb
This fixes the `create_organizations_enabled_connection` method, which ommitted the require `connection_id`
=> Fixes create_organizations_enabled_connection

CHANGELOG.md, lib/auth0/version.rb
[Full Changelog](https://github.com/auth0/ruby-auth0/compare/v5.1.0..v5.1.1)
**Fixed**
- Fixes create_organizations_enabled_connection [\#269](https://github.com/auth0/ruby-auth0/pull/269) ([davidpatrick](https://github.com/apps/davidpatrick))
=> Release 5.1.1

lib/auth0/exception.rb, spec/lib/auth0/mixins/httpproxy_spec.rb
I noticed that we had type error when we were trying to get the `.reset`
time in an RateLimitEncountered. Headers are symbolized and are not
strings.
To reproduce de behavior I did
```ruby
t = []
85.times do
t << Thread.new do
auth0_client.clients
rescue Auth0::RateLimitEncountered => e
puts <<~DOC
exception: #{e.inspect}
reset: #{e.reset}
DOC
end
end
end; nil
p t.map(&:join); nil
p 1
```
Without the fix
```
.../gems/activesupport-6.0.3.6/lib/active_support/core_ext/time/calculations.rb:53:in `at': can't convert nil into an exact number (TypeError)
```
Inspecting headers:
```
headers['X-RateLimit-Reset']: nil, headers[:x_ratelimit_reset]: 1619192310
```
With the fix:
```
exception: #<Auth0::RateLimitEncountered: {"statusCode":429,"error":"Too Many Requests","message":"Global limit has …
```
=> Properly handle headers when parsing x_ratelimit_reset in exception

lib/auth0/mixins/httpproxy.rb
When making bulk imports with `import_users`, the default `Content-Type` headers (`application/json`)
should not be used, since there is a file in the payload.
The RestClient client fixes that and replaces this header with its own (thank you RestClient), but it
emits a warning, and it's still a mistake.
Since generating headers for a multipart POST request is a bit annoying, I've chosen to simply _remove_
the `Content-Type` headers, and let RestClient do the work.
=> Allow RestClient to set Content-Type Headers on bulk imports

auth0.gemspec
This bumps the dependency version on the addressable gem, as version 2.7 is covered by CVE-2021-32740
Also covered by a GHSA at https://github.com/advisories/GHSA-jxhc-q857-3j6g
Once this passes, we should probably bump the gem version and release an updated gem so that users of this gem can upgrade addressable.
=> bump addressable version per CVE-2021-32740

CHANGELOG.md, lib/auth0/version.rb
**Security**
- Bump addressable version per CVE-2021-32740 [\#276](https://github.com/auth0/ruby-auth0/pull/276) ([lostapathy](https://github.com/lostapathy))
=> Release 5.1.2

README.md, lib/auth0/api/v2/connections.rb, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/_connection/_filters/should_exclude_the_fields_indicated.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/_connection/_filters/should_include_the_fields_indicated.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/_connection/should_find_the_correct_connection.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/_connections/_filters/should_include_previously-created_connection_when_filtered.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/_connections/_filters/should_should_exclude_the_fields_indicated_from_filtered_results.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/_connections/_filters/should_should_include_the_fields_indicated_from_filtered_results.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/_connections/should_include_the_previously_created_connection.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/_connections/should_not_be_empty.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/_delete_connection/should_delete_the_connection.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/_delete_connection_user/should_delete_the_user_created.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/_update_connection/should_update_the_connection.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/create_test_connection.yml, spec/lib/auth0/api/v2/connections_spec.rb
This PR modifies the `delete_connection_user` method, putting the `email` query param inside the `body` hash parameter of the `delete` method, so it gets properly encoded and added as a query param to the URL by the [rest-client](https://github.com/rest-client/rest-client) gem.
Previously, this query param was added directly to the endpoint path, which resulted in it not being properly percent-encoded (the reserved characters [as per RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-2.2) were not encoded). This resulted in the [endpoint](https://auth0.com/docs/api/management/v2#!/Connections/delete_users_by_email) returning an error due to the input validation failed with emails like `foo+tag@example.com`, because `+` was not percent-encoded.
See similar instance: …
=> Ensure email param is properly encoded in `delete_connection_user` [SDK-2660]

auth0.gemspec
Overly restrictive version locks will [cause unnecessary issues for downstream applications](https://github.com/auth0/ruby-auth0/issues/277). All gems should be following semver, such that minor version bumps are completely backwards compatible. By fuzzy locking to the minor version that you need, you both allow upgrading to compatible newer versions, while also ensuring the inclusion of functionality that may have been introduced in a minor version.
=> Do not lock dependencies to minor version

lib/auth0/api/v2/device_credentials.rb, spec/lib/auth0/api/v2/device_credentials_spec.rb
Adds `rotating_refresh_token` to the allowed device credential types. The `rotating_refresh_token` is valid in the [Auth0 Management API](https://auth0.com/docs/api/management/v2#!/Device_Credentials/get_device_credentials) but the documentation request schema is not updated.
Support ticket: https://support.auth0.com/tickets/00492497
=> Adds Rotating Refresh Token type to Device Credentials

CHANGELOG.md, lib/auth0/version.rb
[Full Changelog](https://github.com/auth0/ruby-auth0/compare/v5.1.2..v5.2.0)
**Fixed**
- Ensure email param is properly encoded in delete_connection_user [\#280](https://github.com/auth0/ruby-auth0/pull/280) ([widcket](https://github.com/widcket))
**Added**
- Adds Rotating Refresh Token type to Device Credentials [\#275](https://github.com/auth0/ruby-auth0/pull/275) ([epintos](https://github.com/epintos))
**Changed**
- Do not lock dependencies to minor version [\#279](https://github.com/auth0/ruby-auth0/pull/279) ([athix](https://github.com/athix))
=> Release 5.2.0

lib/auth0/api/v2/logs.rb, lib/auth0/api/v2/organizations.rb, lib/auth0/api/v2/roles.rb, spec/lib/auth0/api/v2/organizations_spec.rb, spec/lib/auth0/api/v2/roles_spec.rb
This PR includes method documentation (docblock) updates to reflect the availability of checkpoint pagination parameters on supported endpoints. It does not add any new functionality or require new tests.
Please see the internal Jira tickets SDK-2667 and related epic SDK-2653 for details on this initiative.
=> Document checkpoint pagination params [SDK-2667]

lib/auth0/mixins/httpproxy.rb, spec/lib/auth0/mixins/httpproxy_spec.rb, spec/support/dummy_class_for_proxy.rb
When encoding the uri, we currently have two different strategies, either the full URL or the path.  When passing in just the path, the Addressable aggresively parses the path assuming its a full url.  This causes some charachters to not be encoded and instead be parsing points of the url.
This PR changes the strategy to check for when the base_uri is set, and if is is we dont need to parse the url, just encode the path.
=> Change strategy when normalizing path

CHANGELOG.md, lib/auth0/version.rb
[Full Changelog](https://github.com/auth0/ruby-auth0/compare/v5.3.0..v5.4.0)
**Fixed**
- Fixing yard issues with documentation [\#288](https://github.com/auth0/ruby-auth0/pull/288) ([davidpatrick](https://github.com/davidpatrick))
**Changed**
- Change strategy when normalizing path [\#287](https://github.com/auth0/ruby-auth0/pull/287) ([davidpatrick](https://github.com/davidpatrick))
=> Bump to 5.4.0

auth0.gemspec, lib/auth0/mixins/httpproxy.rb, lib/auth0/mixins/initializer.rb, spec/lib/auth0/mixins/httpproxy_spec.rb, spec/lib/auth0/mixins/initializer_spec.rb
This PR enables support for automatic retry of API requests that encounter a 429 rate-limit status response from the Auth0 API. It will retry, by default, up to 3 times, with a hard-coded cap of 10. It exponentially increases the delay between each request ("exponential backoff"), and uses a jitter technique to slightly randomize the variance of this delay.
Please see the internal SDK-2653 epic on this topic.
Coverage added ✅ 
existing tests also ✅
=> [SDK-2689] Automatically retry requests when API returns a 429 rate-limit status header. 

CHANGELOG.md, lib/auth0/version.rb
[Full Changelog](https://github.com/auth0/ruby-auth0/compare/v5.4.0..v5.5.0)
**Added**
- Automatically retry requests when API returns a 429 rate-limit status header. [\#290](https://github.com/auth0/ruby-auth0/pull/290) ([davidpatrick](https://github.com/davidpatrick))
=> Bump to 5.5.0

lib/auth0/api/v2.rb, lib/auth0/api/v2/actions.rb, lib/auth0/exception.rb, spec/lib/auth0/api/v2/actions_spec.rb
=> [SDK-2718] New Actions endpoints

lib/auth0/api/authentication_endpoints.rb
The method `change_password` took a password argument that was only supported on legacy tenants with the flag `change_pwd_flow_v1` enabled.  In order to resolve confusion, we're introducing a new method `reset_password` to fire off a password reset email, and deprecating the old method.
Fixes #292
=> Deprecate change_password in favor of reset_password

lib/auth0/api/v2/grants.rb, spec/lib/auth0/api/v2/grants_spec.rb
This PR fixes https://github.com/auth0/ruby-auth0/issues/303.
A request way for `DELETE /api/v2/grants/{id?}` was changed.
https://github.com/auth0/ruby-auth0/issues/303
=> Fix how to call delete_grant API

CHANGELOG.md, lib/auth0/version.rb
**Fixed**
- Fix `delete_grant` API call [\#304](https://github.com/auth0/ruby-auth0/pull/304) ([danimal141](https://github.com/danimal141))
=> Release v5.6.1

lib/auth0/api/v2/organizations.rb, spec/lib/auth0/api/v2/organizations_spec.rb
delete_organizations_member_roles should use delete_with_body instead of delete
Please describe both what is changing and why this is important. Include:
- Endpoints added, deleted, deprecated, or changed
- Classes and methods added, deleted, deprecated, or changed
- Screenshots of new or changed UI, if applicable
- A summary of usage if this is a new feature or change to a public API (this should also be added to relevant documentation once released)
=> Fix #310: delete_organizations_member_roles should use delete_with_body instead of delete

lib/auth0/api/v2.rb, lib/auth0/api/v2/attack_protection.rb, spec/lib/auth0/api/v2/attack_protection_spec.rb
This PR adds support for the following Attack Protection endpoints for the Auth0 Management API:
```
GET /api/v2/attack-protection/breached-password-detection
PATCH /api/v2/attack-protection/breached-password-detection
GET /api/v2/attack-protection/brute-force-protection
PATCH /api/v2/attack-protection/brute-force-protection
GET /api/v2/attack-protection/suspicious-ip-throttling
PATCH /api/v2/attack-protection/suspicious-ip-throttling
```
=> [SDK-3118] Add attack protection endpoints

lib/auth0/api/v2/device_credentials.rb, spec/lib/auth0/api/v2/device_credentials_spec.rb
I added `page`, `per_page`, `include_totals` parameters to device_credentials method, because [API documents](https://auth0.com/docs/api/management/v2#!/Device_Credentials/get_device_credentials) describe that Retrieve device credentials API has parameters for pagerize.
No References
* I found some offenses by rubocop in lib/auth0/api/v2/device_credentials.rb and spec/lib/auth0/api/v2/device_credentials_spec.rb.  But I left it at that because there were originally many offenses
=> Add parameters for pager to device_credentials method

README.md
Correct controller filename in example found in README.md 
from:
`app/controllers/all_users_controllers.rb`
to:
`app/controllers/all_users_controllers.rb`
=> Fix incorrect controller filename in the example

lib/auth0/api/authentication_endpoints.rb
Fix the wrong method name in the document.
-
-
=> Fix 'password_reset' -> 'reset_password'

lib/auth0/mixins/validation.rb, spec/lib/auth0/mixins/validation_spec.rb
Fixes #324
The underlying issue is discussed in #324, but in summary, JWT validation using RS256 caches the JWKS for the entire runtime, even if multiple Auth0 tenants (varying JWKS URLs are in use). This change caches the JWKS per JWKS url instead of using just a generic cache key. This allows applications that use multiple Auth0 tenants to properly cache their JWKS and avoid unnecessary HTTP requests to pull the well-known JWKS.  Otherwise, the JWKS cache thrashes itself while switching between multiple Auth0 tenants.
Fixes #324
=> Cache RS256 JWKS by url to allow for multiple Auth0 tenants per runtime

lib/auth0/api/v2/organizations.rb, spec/lib/auth0/api/v2/organizations_spec.rb
- The API `delete_organizations_members` does not work as described in https://auth0.com/docs/api/management/v2#!/Organizations/delete_members. It does not send `members` in body. 
```
RestClient.delete "https://tinypulse-dev.us.auth0.com/api/v2/organizations/org_RuiZ53NZmzht7toO/members?members[]=auth0%7C90262", "Accept"=>"*/*", "Auth0-Client"=>"...", "Authorization"=>"Bearer ...", "Content-Type"=>"application/json", "User-Agent"=>"rest-client/2.1.0 (darwin21.4.0 aarch64) ruby/2.6.10p210"
Auth0::BadRequest ({"statusCode":400,"error":"Bad Request","message":"Payload validation error: 'Expected type object but found type null'.","errorCode":"invalid_body"})
```
- Use `delete_with_body` instead of `delete` for `delete_organizations_members` to send body
Please describe how this can be …
=> FIX: delete_organizations_members does not send `members` in body

.circleci/config.yml, Gemfile, Gemfile.lock, spec/spec_helper.rb
This PR replaces the deprecated Codecov bash uploader with the current recommended path for CircleCI, an Orb. It updates the Simplecov dependency to generate a coverage clover suitable for this use.
See internal ticket SDK-3464
=> [SDK-3463] Update Codecov

lib/auth0/api/v2/connections.rb, spec/lib/auth0/api/v2/connections_spec.rb
This PR adds the `include_totals` option to `GET connections` API2 endpoint method.
Fixes #349
=> Add include_totals to get connections options

lib/auth0/api/v2/users.rb
Changes the doc comments for `User.remove_user_roles`.  It erroneously says it takes role *names*, but it actually needs role *ids*.
See the [API docs for this endpoint](https://auth0.com/docs/api/management/v2#!/Users/delete_permissions); in the samples sidebar it says
> roles: List of roles IDs to remove from the user"
Here's a screenshot:
This isn't a code change (just a doc change), so no tests to change/update.
=> correct remove_user_roles doc: roles param is ids, not names

lib/auth0/api/v2/users.rb, spec/lib/auth0/api/v2/users_spec.rb
This PR to add `delete_user_authenticators` to `Users` API to implement https://auth0.com/docs/api/management/v2#!/Users/delete_authenticators
=> Add Delete All Authenticators API for Users

CHANGELOG.md, Gemfile.lock, lib/auth0/version.rb
**Added**
- Add Delete All Authenticators API for Users [\#375](https://github.com/auth0/ruby-auth0/pull/375) ([phongnh](https://github.com/phongnh))
**Changed**
- Add include_totals to get connections options [\#357](https://github.com/auth0/ruby-auth0/pull/357) ([stevehobbsdev](https://github.com/stevehobbsdev))
**Fixed**
- Fix typo and remove param that is not used [\#365](https://github.com/auth0/ruby-auth0/pull/365) ([MatthewRDodds](https://github.com/MatthewRDodds))
- correct remove_user_roles doc: roles param is ids, not names [\#359](https://github.com/auth0/ruby-auth0/pull/359) ([gbirchmeier](https://github.com/gbirchmeier))
=> Release v5.9.0

.circleci/config.yml, Gemfile, Gemfile.lock, auth0.gemspec, lib/auth0/mixins/token_management.rb, spec/lib/auth0/mixins/httpproxy_spec.rb, spec/lib/auth0/mixins/token_management_spec.rb, spec/spec_helper.rb
This PR unpins `jwt` from `2.3.x` and allows `2.5.x`. In addition, CI has been updated to only test [officially-supported Ruby versions](https://endoflife.date/ruby).
Fixes #369
=> [SDK-3643] Update jwt ~2.5

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, lib/auth0/mixins/httpproxy.rb
The rate limiting wasn't very effective, always sitting at 1 second without any exponential backoff. These changes reconfigure the backoff so that there is progressive limiting until it hits 1 second.
Sample output over 10 retries:
```shell
0.25
0.369
0.803
1.0
1.0
1.0
1.0
1.0
1.0
1.0
```
Closes #358
=> [SDK-3644] Reconfigure rate limiting exponential backoff

lib/auth0/api/v2/jobs.rb, spec/lib/auth0/api/v2/jobs_spec.rb
This PR tweaks `export_users` so that it could now accept (and properly forward) field names and `export_as` settings to the `jobs/users-exports` endpoint. Previously it was only possible to specify an array of field strings. Now, objects can be specified meaning that the `export_as` property can be specified.
This is done in a backwards-compatible way so as not to break those still sending string arrays.
Usage example:
```ruby
auth0.export_users(
fields: [{ name: 'author', export_as: 'creator' }],
connection_id: 'test-connection',
format: 'csv',
limit: 10
)
```
Fixes #378 
Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing …
=> [SDK-3642] feat: support complex field names in export_users

lib/auth0/mixins/httpproxy.rb, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Clients/_patch_client/should_update_the_client_with_the_correct_attributes.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Connections/_update_connection/should_update_the_connection.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Rules/_update_rule/should_update_the_disabled_rule_to_be_enabled.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Tenants/_update_tenant_settings/should_revert_the_tenant_name.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Tenants/_update_tenant_settings/should_update_the_tenant_settings_with_a_new_tenant_name.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Users/_add_user_roles/should_add_a_Role_to_a_User_successfully.yml, spec/fixtures/vcr_cassettes/Auth0_Api_V2_Users/_patch_user/should_patch_the_User_successfully.yml, spec/lib/auth0/mixins/httpproxy_spec.rb
This change means that parameters supplied to a `:get` or `:delete` request in `RestClient` should no longer bleed into subsequent calls, as the shared headers hash is no longer mutated by these calls.
This fix has caused some of the integration test fixtures to no longer match requests being made, so these have also been updated.
Fixes #344
=> fix: stop :get, :delete parameters from bleeding into subsequent requests

CHANGELOG.md, Gemfile.lock, lib/auth0/version.rb
**Changed**
- Update jwt ~2.5 [\#384](https://github.com/auth0/ruby-auth0/pull/384) ([stevehobbsdev](https://github.com/stevehobbsdev))
**Fixed**
- fix: stop :get, :delete parameters from bleeding into subsequent requests [\#388](https://github.com/auth0/ruby-auth0/pull/388) ([stevehobbsdev](https://github.com/stevehobbsdev))
- Support complex field names in export_users [\#387](https://github.com/auth0/ruby-auth0/pull/387) ([stevehobbsdev](https://github.com/stevehobbsdev))
- Reconfigure rate limiting exponential backoff [\#386](https://github.com/auth0/ruby-auth0/pull/386) ([stevehobbsdev](https://github.com/stevehobbsdev))
=> Release v5.10.0

examples/ruby-on-rails-api/README.md
This PR removes an outdated/obsolete link from one of the examples.
-
=> fix: Remove obsolete example link

EXAMPLES.md, lib/auth0/api/authentication_endpoints.rb, lib/auth0/client_assertion.rb, lib/auth0/mixins/initializer.rb, lib/auth0/mixins/token_management.rb, spec/lib/auth0/api/authentication_endpoints_spec.rb, spec/lib/auth0/mixins/initializer_spec.rb, spec/lib/auth0/mixins/token_management_spec.rb, spec/support/dummy_class_for_tokens.rb
This PR adds support for specifying an asymmetric key for the purposes of signing a client assertion JWT to authenticate with Auth0, as an alternative to `client_secret`. See [Private Key Jwt](https://oauth.net/private-key-jwt/).
With these changes, the SDK accepts two new arguments on client creation:
- `client_assertion_signing_key`: A key used for signing the client assertion JWT (the corresponding public key should be uploaded to your Auth0 tenant)
- `client_assertion_signing_alg`: The signing algorithm to use (defaults to `RS256` if not specified
The `client_secret` argument can then be omitted. If both `client_secret` and `client_assertion_signing_key` are specified, the latter takes precedence.
The key can be anything accepted by [`ruby-jwt`](https://github.com/jwt/ruby-jwt). …
=> [SDK-3863] Add support for Client Assertion in authentication endpoints

.circleci/config.yml, .devcontainer/devcontainer.json, Gemfile.lock, auth0.gemspec, spec/spec_helper.rb
This PR removes `pry` (a debug tool) from the dev dependency list, it wasn't being actively used other than being required. It's a useful tool but has been superseded in 3.2 with new built-in debug tools.
Including it produces an error that is fixed in `pry@0.14`, but unable to upgrade to that version thanks to an incompatible transient dependency chain.
However, removing it means the SDK can be tested in Ruby 3.2.
=> ci: include Ruby 3.2 in test matrix

lib/auth0/api/v2/clients.rb, spec/lib/auth0/api/v2/clients_spec.rb
This PR adds support for the following new management client endpoints:
- `POST /clients/<client_id>/credentials`
- `GET /clients/<client_id>/credentials`
- `GET /clients/<client_id>/credentials/<credential_id>`
- `DELETE /clients/<client_id>/credentials/<credential_id>`
=> [SDK-3869] Support client credentials in management client

lib/auth0/api/authentication_endpoints.rb, spec/lib/auth0/api/authentication_endpoints_spec.rb, spec/lib/auth0/api/v2/clients_spec.rb
This adds two methods `exchange_email_otp_for_tokens` and `exchange_sms_otp_for_tokens` for completing the email and SMS embedded passwordless flows respectively. This is essentially a missing feature; the SDK already supports starting the flows but provides no affordances to be able to complete them.
Also supports authentication using client assertion.
The Auth0 client must have the "Passwordless OTP" grant enabled (see [Passwordless embedded login](https://auth0.com/docs/authenticate/passwordless/implement-login/embedded-login/relevant-api-endpoints#post-oauth-token)).
Usage example:
```ruby
client = Auth0Client.new domain: 'YOUR_AUTH0_DOMAIN', client_id: 'YOUR_CLIENT_ID', client_secret: 'YOUR_CLIENT_SECRET'
client.start_passwordless_email_flow 'email@test.com', 'code' …
```
=> feat: support exchanging OTP codes for tokens

.circleci/config.yml, lib/auth0/api/v2/users.rb, spec/lib/auth0/api/v2/users_spec.rb
This PR adds support for the User Authentication Method endpoints in the Auth0 management API.
Endpoint | Description
----|----
`GET /api/v2/users/{user_id}/authentication-methods` | Get all authentication methods for a user
`GET /api/v2/users/{user_id}/authentication-methods/{id}` | Get an authentication method  for a user by ID
`POST /api/v2/users/{user_id}/authentication-methods` | Create a new authentication method for a user
`PUT /api/v2/users/{user_id}/authentication-methods` | Update all authentication methods
`PATCH /api/v2/users/{user_id}/authentication-methods/{id}` | Update one authentication method for a user by ID
`DELETE /api/v2/users/{user_id}/authentication-methods` | Delete all authentication methods for a user
`DELETE /api/v2/users/{user_id}/authentication-methods/{id}` …
=> [SDK-4014] User Authentication Method management API support

.circleci/config.yml
This PR resolves a break in the CircleCI configuration for Codecov which resulted in coverage files not being uploaded.
N/A
=> chore: Fix Codecov uploader in CI

lib/auth0/api/authentication_endpoints.rb, lib/auth0/mixins/httpproxy.rb, spec/lib/auth0/api/authentication_endpoints_spec.rb, spec/lib/auth0/mixins/httpproxy_spec.rb, spec/support/dummy_class_for_tokens.rb
This PR implements two new auth API methods:
* `pushed_authorization_request`: calls the `/oauth/par` endpoint with all the parameters that would normally be sent to `/authorize`, and returns the payload including `request_uri`
* `par_authorization_url`: accepts `request_uri` and builds a URL that includes it along with `client_id`
Something I would like some feedback on: the SDK already exposes `authorization_url` ([source](https://github.com/auth0/ruby-auth0/blob/7d6bfa7e595d0893b71cad2889c7a4f20c8c7c60/lib/auth0/api/authentication_endpoints.rb#L309)) that builds a URL for `/authorize` with all the params. However, I decided not to support PAR here for two reasons:
* It currently takes a required parameter `redirect_url` that is not required for the PAR request
* It currently takes a …
=> [SDK-4142] Add support for /oauth/par

.devcontainer/Dockerfile, EXAMPLES.md, Gemfile.lock, auth0.gemspec, lib/auth0/mixins/validation.rb, spec/lib/auth0/mixins/validation_spec.rb
This PR enables support for authorizing using organization name in addition to organization ID. Docs also updated.
In addition, some tweaks were made to organization tests that allow dynamic generation of the ID token as opposed to using a hard-coded value.
**Note:** use of this feature requires your Auth0 tenant to have this feature enabled.
=> [SDK-4386] Support Organization Name in Authorize

CHANGELOG.md, Gemfile.lock, lib/auth0/version.rb
**Fixed**
- chore: should not lowercase org_name claim [\#499](https://github.com/auth0/ruby-auth0/pull/499) ([stevehobbsdev](https://github.com/stevehobbsdev))
=> Release v5.14.1

Gemfile.lock, auth0.gemspec
This is not used by the SDK and was added way in the past to fix a build issue at the time. Today, however, it's causing a [Snyk vulnerability check failure](https://github.com/auth0/ruby-auth0/actions/runs/6346425109/job/17239905440).
=> chore: remove rack dev dependencies

lib/auth0/api/authentication_endpoints.rb, lib/auth0/api/v2/client_grants.rb, lib/auth0/api/v2/organizations.rb, spec/lib/auth0/api/authentication_endpoints_spec.rb, spec/lib/auth0/api/v2/client_grants_spec.rb, spec/lib/auth0/api/v2/organizations_spec.rb, spec/lib/auth0/mixins/initializer_spec.rb, spec/lib/auth0/mixins/token_management_spec.rb
- Add optional organization parameter to client credentials grant
- Add Management API endpoints to /client-grants and /organizations
=> [SDK-4546] Add orgs in client credentials support

CHANGELOG.md, Gemfile.lock, lib/auth0/version.rb
**Added**
- [SDK-4546] Add orgs in client credentials support [\#540](https://github.com/auth0/ruby-auth0/pull/540) ([adamjmcgrath](https://github.com/adamjmcgrath))
[SDK-4546]: https://auth0team.atlassian.net/browse/SDK-4546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Release v5.16.0

lib/auth0/api/v2.rb, lib/auth0/api/v2/sessions.rb, spec/lib/auth0/api/v2/sessions_spec.rb
Add support for the Session resource endpoints in the Management API.
https://github.com/auth0/ruby-auth0/pull/613
=> Add Management API calls for session API endpoints #613

lib/auth0/api/v2.rb, lib/auth0/api/v2/refresh_tokens.rb, lib/auth0/api/v2/users.rb, spec/lib/auth0/api/v2/refresh_tokens_spec.rb, spec/lib/auth0/api/v2/users_spec.rb
Adds support for the Management API endpoints introduced in [Manage Refresh Tokens with Auth0 Management API](https://auth0.com/docs/secure/tokens/manage-refresh-tokens-with-auth0-management-api)
https://github.com/auth0/ruby-auth0/pull/614
=> Add Refresh Token endpoints for the Auth0 Management API #614
